### ISSUE TITLE
(I think) You have to re-initialize the model inside for

### ISSUE THREAD

**Issue by SqrtPapere** [MrDupin/Machine-Learning#3]
I once realised that my model improved from 61% accuracy to 84% during the 5-fold cross validation.
This is why each time it trains an already trained model!
You have to wrap the model creation in a function like `create_model()`and call it inside the for loop before `fit()`

**Comment by antmarakis** [comment]
Hmm, I am not sure where this issue is. Do you remember the script where you found this?

**Comment by SqrtPapere** [comment]
In the [kFold.py](https://github.com/MrDupin/Machine-Learning/blob/master/Keras/kFold.py) script.

**Comment by antmarakis** [comment]
Good catch, thanks!

[I believe I fixed it now](https://github.com/MrDupin/Machine-Learning/commit/daccdf8daf4de3a040d79f5b7b386627828a885f).
